language: python
python:
  - "2.7"
  - "3.5"
  - "3.8"

cache:
  directories:
  - "$HOME/.cache/pip"

install:
  - pip install -r requirements.txt
  - pip install pytest hypothesis
  - pip install .

script:
  - pytest
